# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c676285b541ce81cd7aa6567ae2d3e4cac7ccaa5e4af2182e7dde6ac4c2820800f9f1f3a51b37b1a330b7c562afe77279e29f6c0888a2995d835f4381e0517c

test:
  secret_key_base: 702edd165d89f4ef8f141492df8fa7b28d61991c9bd20bcd9334f05abb5d2342ca0f929640a85ee3479bf49dccaaecf4b85edb57e204c80a620f9082fb5074dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
